### PR TITLE
add function to check NYT API limits and usage

### PR DESCRIPTION
**Pull request by andybega**
- adds api_limits() for checking NYT API daily limit and how many have been used
- adds tests for api_limits()

### CODE REVIEW

**Comment by andybega** [comment]
Hi,
when I was trying to replicate something like the code in your NYT civil rights vignette to get yearly counts for several keywords, I accidentally exceeded my daily limit for queries (in between wasting API calls with code that had errors and using a dozen keywords + several decades). The NYT API FAQ has a line on how to make a header request to get states on the daily limit, https://developer.nytimes.com/faq#9, which the function this adds `api_limits()` is based on.

I checked locally with `devtools::test()` and devtools::check()` and there were no errors/warnings/notes. The test code sometimes causes the API to complain about too many requests, but aside from that it seems to work fine. The check output is below. I see that it is failing on Travis because the API keys environment variable is missing, not sure how to fix that. 

```
> devtools::check()
Updating rtimes documentation
Loading rtimes
Setting env vars ---------------------------------------------------------------------
CFLAGS  : -Wall -pedantic
CXXFLAGS: -Wall -pedantic
Building rtimes ----------------------------------------------------------------------
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD build '/Users/andybega/Work/R-packages/rtimes'  \
  --no-resave-data --no-manual 

* checking for file ‘/Users/andybega/Work/R-packages/rtimes/DESCRIPTION’ ... OK
* preparing ‘rtimes’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
Removed empty directory ‘rtimes/man-roxygen’
* building ‘rtimes_0.5.0.9151.tar.gz’

Setting env vars ---------------------------------------------------------------------
_R_CHECK_CRAN_INCOMING_USE_ASPELL_: TRUE
_R_CHECK_CRAN_INCOMING_           : FALSE
_R_CHECK_FORCE_SUGGESTS_          : FALSE
Checking rtimes ----------------------------------------------------------------------
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD check  \
  '/var/folders/54/f1wx41c56mv074yyp235c9s00000gn/T//RtmpPKXWy1/rtimes_0.5.0.9151.tar.gz'  \
  --as-cran --timings --no-manual 

* using log directory ‘/private/var/folders/54/f1wx41c56mv074yyp235c9s00000gn/T/RtmpPKXWy1/rtimes.Rcheck’
* using R version 3.4.2 Patched (2017-10-03 r73455)
* using platform: x86_64-apple-darwin15.6.0 (64-bit)
* using session charset: UTF-8
* using options ‘--no-manual --as-cran’
* checking for file ‘rtimes/DESCRIPTION’ ... OK
* this is package ‘rtimes’ version ‘0.5.0.9151’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘rtimes’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘test-all.R’
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking re-building of vignette outputs ... OK
* DONE

Status: OK

R CMD check results
0 errors | 0 warnings | 0 notes
```

**Comment by andybega** [comment]
Oh, and here is example output:

```
> api_limits("as")
$limit_per_day
[1] 1000

$remaining_today
[1] 969

$used_today
[1] 31
```

**Comment by sckott** [comment]
thanks @andybega !

the failure on PR's is b/c env vars are not available to PR builds on Travis, so no problem there most likely. 

I'll have a look ...

**Comment by sckott** [comment]
mostly looks good, but `geo` doesn't work

returns a 500 error (aside, which prob, should be a 400 series error since that seems like a client side error)

```json
{
  "status": "ERROR",
  "copyright": "Copyright (c) 2015 The New York Times Company. All Rights Reserved.",
  "errors": [
    "Specify at least one filter"
  ],
  "results": []
}
```

I think if we put in a single parameter to the geo query, e.g., `&country_code=EE`, then it should be fine.

**Comment by andybega** [comment]
Thanks @sckott, that fix worked.

**Comment by sckott** [comment]
great, thank so much for this

**Pull request merged**
