### PR TITLE
Paginate API response and retrieve all articles

### PR DESCRIPTION
**Pull request by toledobastos**
I wrote a wrapper to your wrapper so it now paginates the API response and retrieves all articles. Fell free to change the code as you see fit.

### CODE REVIEW

**Comment by sckott** [comment]
thanks @toledobastos I'll have a look and get back to you

**Comment by sckott** [comment]
Looking at the code, seems like there's two things you want:

1. get all results in one call
2. get back a data.frame instead of a S3 class/list object

Would you mind if we just add this to `as_search` ? We can add __1__ with a parameter and some internal changes, and __2__ with another parameter to toggle what is returned

here's the draft function modified to get all results (but not data.frame yet)

```r
#' @examples 
#' as_search2(q="bailout", begin_date = "20081001", 
#'   end_date = '20081005')
#' as_search2(q="bailout", begin_date = "20081001", 
#'   end_date = '20081005', all_results=TRUE)

`as_search2` <- function(
  q, fq=NULL, sort=NULL, begin_date=NULL, end_date=NULL,
  key = NULL, fl = NULL, hl = FALSE,
  page = 0, all_results = FALSE, facet_field = NULL, 
  facet_filter = NULL, sleep = 2, ..., callopts=list()) {
  
  if(!is.null(begin_date)) {
    if(is.null(end_date))
      end_date = Sys.Date()
    if(inherits(begin_date, "POSIXt") )
      begin_date = format(begin_date, "%Y%m%d")
    if(inherits(end_date, "POSIXt") )
      end_date = format(end_date, "%Y%m%d")
  }
  if(!is.null(fl)) fl = paste(fl, collapse = ",")
  if(!is.null(facet_field)){
    if(length(facet_field)) {
      if(length(facet_field) > 5)
        stop("Only 5 facets allowed")
      facet_field = paste(facet_field, collapse = ",")
    }
  }
  if(!is.logical(hl)) stop("hl parameter must be logical")
  if(hl){ hl = 'true' } else { hl = NULL }
  args <- rc(list(q=q, fl=fl, fq=fq, sort=sort, hl=hl, page=page,
                  begin_date=begin_date, end_date=end_date, 
                  `api-key` = check_key(key, "NYTIMES_AS_KEY"),
                  facet_field=facet_field, facet_filter=facet_filter))
  res <- rtimes_GET(paste0(t_base(), "search/v2/articlesearch.json"), c(args, ...), 
                    callopts, ...)
  if (all_results) {
    hits <- res$response$meta$hits
    pgs <- 1:floor(hits/10)
    out <- list()
    pb <- txtProgressBar(min = 0, max = length(pgs), initial = 0, style = 3)
    on.exit(close(pb))
    for (i in seq_along(pgs)) {
      Sys.sleep(sleep)
      setTxtProgressBar(pb, i)
      args$page <- pgs[i]
      out[[i]] <- rtimes_GET(paste0(t_base(), "search/v2/articlesearch.json"), c(args, ...), 
                        callopts, ...)
    }
    
    dat <- lapply(out, function(z) {
      if (is.null(fl)) {
        lapply(z$response$docs, structure, class="as_search") 
      } else {
        z$response
      }
    })
    meta <- NULL
  } else {
    dat <- if (is.null(fl)) {
      lapply(res$response$docs, structure, class="as_search") 
    } else {
      res$response
    }
    meta <- as_meta(res)
  }
  
  list(copyright=cright(), meta=meta, data=dat)
}
```

seem good to you?

I do appreciate the PR, but I'd rather reduce code duplication, and keep style consistent, etc.

**Comment by toledobastos** [comment]
That looks good and it's deffo better to keep style consistency. Transforming the S3 object to data frame is a bit tricky. Hopefully you can manage to fill out the data frame without a loop. That would be ideal.

**Comment by sckott** [comment]
We can do the data.frame without a loop, is this acceptable:

```r
# A tibble: 10 × 24
                                                                                       web_url
*                                                                                        <chr>
1                              http://www.nytimes.com/2008/10/05/magazine/05wwln-safire-t.html
2                              http://krugman.blogs.nytimes.com/2008/10/01/bailout-narratives/
3                          http://economix.blogs.nytimes.com/2008/10/03/musical-bailout-humor/
4                             http://economix.blogs.nytimes.com/2008/10/02/more-bailout-humor/
5                 http://tmagazine.blogs.nytimes.com/2008/10/01/quote-unquote-fashion-bailout/
6  http://economix.blogs.nytimes.com/2008/10/03/economists-bailout-petitions-migrate-eastward/
7                  http://krugman.blogs.nytimes.com/2008/10/03/has-the-bailout-already-failed/
8                                  http://www.nytimes.com/2008/10/03/business/03naysayers.html
9         http://dealbook.nytimes.com/2008/10/01/group-of-economists-rally-around-the-bailout/
10            http://dealbook.nytimes.com/2008/10/03/a-curious-coalition-opposed-bailout-bill/
# ... with 23 more variables: snippet <chr>, lead_paragraph <chr>, abstract <chr>, print_page <chr>, blog <list>,
#   source <chr>, multimedia <list>, keywords <list>, pub_date <chr>, document_type <chr>, news_desk <chr>,
#   section_name <chr>, subsection_name <lgl>, type_of_material <chr>, `_id` <chr>, word_count <chr>,
#   slideshow_credits <lgl>, headline.main <chr>, headline.content_kicker <chr>, headline.kicker <chr>,
#   headline.print_headline <chr>, byline.person <list>, byline.original <chr>
```

The data.frame is made by using `jsonlite::fromJSON(x, TRUE, flatten = TRUE)` so that we can easily get to a data.frame shape, but this means there's data.frame's nested within the main data.frame, e.g, here's the first few set of columns from the above data.frame

```r
str(x$data)
#> Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	10 obs. of  24 variables:
#>  $ web_url                : chr  "http://www.nytimes.com/2008/10/05/magazine/05wwln-safire-t.html" "http://krugman.blogs.nytimes.com/2008/10/01/bailout-narratives/" "http://economix.blogs.nytimes.com/2008/10/03/musical-bailout-humor/" "http://economix.blogs.nytimes.com/2008/10/02/more-bailout-humor/" ...
#>  $ snippet                : chr  "How can you be naked wearing shorts?..." "There seem to be two prevailing narratives about the bailout plan(s). Both have elements of truth, but are fundamentally wrong."| __truncated__ "A song about the bailout...." "Laid off by Lehman? Apply for a job at Strategery Capital Management...." ...
#>  $ lead_paragraph         : chr  "How can you be naked wearing shorts?" "There seem to be two prevailing narratives about the bailout plan(s). Both have elements of truth, but are fundamentally wrong."| __truncated__ "As you may have noticed, I'm a sucker for a bad pun." "Out of work on Wall Street? Apply for a job at Strategery Capital Management." ...
#>  $ abstract               : chr  NA "There seem to be two prevailing narratives about the bailout plan(s). Both have elements of truth, but are fundamentally wrong."| __truncated__ "A song about the bailout." "Laid off by Lehman? Apply for a job at Strategery Capital Management." ...
#>  $ print_page             : chr  "14" NA NA NA ...
#>  $ blog                   :List of 10
#>   ..$ : list()
#>   ..$ : list()
#>   ..$ : list()
#>   ..$ : list()
#>   ..$ : list()
#>   ..$ : list()
#>   ..$ : list()
#>   ..$ : list()
#>   ..$ : list()
#>   ..$ : list()
#>  $ source                 : chr  "The New York Times" "The New York Times" "The New York Times" "The New York Times" ...
#>  $ multimedia             :List of 10
#>   ..$ :'data.frame':	0 obs. of  0 variables
#>   ..$ :'data.frame':	0 obs. of  0 variables
#>   ..$ :'data.frame':	0 obs. of  0 variables
#>   ..$ :'data.frame':	0 obs. of  0 variables
#>   ..$ :'data.frame':	0 obs. of  0 variables
#>   ..$ :'data.frame':	0 obs. of  0 variables
#>   ..$ :'data.frame':	0 obs. of  0 variables
#>   ..$ :'data.frame':	1 obs. of  8 variables:
#>   .. ..$ width              : int 600
#>   .. ..$ url                : chr "images/2008/10/03/business/03naysayers600.jpg"
#>   .. ..$ height             : int 298
```

**Comment by toledobastos** [comment]
Sorry for letting this one slip thru the cracks. Crazy weeks around here. 

Yep. I couldn't find a way to get away with the nested data frame. I usually integrate these functions to my pipeline which will require vectors at some point. So while it might work for some, or most, I need to flatten the JSON output to the point there are no nested data or variables of different length. 

I'd be interested to know if you figure out a way to do that without preallocating a vector and filling it out thru a loop. That could streamline things for me, and not just for this function. 

Cheers,
Marco

**Comment by sckott** [comment]
I could run a fxn across each column and make sure to fix any that need it so that there's no nesting

**Comment by toledobastos** [comment]
That's what I usually do and IIRC that's what I was doing with the snippet I forked. Let me know if you find a scalable solution with a small footprint to flatten nested data. That would be sweet.

**Comment by sckott** [comment]
@toledobastos okay, reinstall from master `devtools::install_github("ropengov/rtimes")`

new `as_search` function gives flat data.frame - with option to get all data - I think it covers everything you wanted.

**Pull request closed without merging**
